"""Declarative base, naming conventions, and shared column mixins.

The naming convention is not cosmetic. Without it, PostgreSQL invents index and
constraint names, Alembic autogenerate cannot match them against the models, and
`downgrade` fails on names it never knew — which is exactly when you need it to
work. Fixing the convention now means every migration round-trips.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Deterministic, greppable constraint names.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:
        ident = getattr(self, "id", None)
        return f"<{type(self).__name__} id={ident}>"


# ── column type helpers ───────────────────────────────────────────────────
def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by the database.

    `gen_random_uuid()` (pgcrypto) rather than a Python-side default, so rows
    created by SQL — the seed script, data migrations, `INSERT … SELECT` — get
    valid ids without going through the ORM.
    """
    return mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def utcnow_column(**kwargs: Any) -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now(), **kwargs)


def enum_type(enum_cls: type[enum.Enum], name: str) -> SAEnum:
    """VARCHAR + CHECK constraint for a Python enum.

    `native_enum=False` avoids PostgreSQL `ENUM` types, and `values_callable`
    stores the enum *value* (`"line_manager"`) rather than the member *name*
    (`"LINE_MANAGER"`) — the value is what the API and the frontend exchange, so
    storing it keeps the database readable against the wire format.
    """
    return SAEnum(
        enum_cls,
        name=name,
        native_enum=False,
        create_constraint=True,
        validate_strings=True,
        values_callable=lambda cls: [member.value for member in cls],
    )


# ── mixins ────────────────────────────────────────────────────────────────
class UUIDPrimaryKeyMixin:
    """UUID primary key. Used by every table except high-volume append-only
    ones (`audit_log`, `notification_outbox`), which use BIGSERIAL."""

    @declared_attr
    @classmethod
    def id(cls) -> Mapped[uuid.UUID]:
        return uuid_pk()


class TimestampMixin:
    """`created_at` / `updated_at`, both TIMESTAMPTZ in UTC.

    `onupdate` is applied Python-side by the ORM; `server_default` covers rows
    written by raw SQL. A trigger would cover both, but it also hides the write
    from the application and complicates the audit diff, so it is deliberately
    not used.
    """

    @declared_attr
    @classmethod
    def created_at(cls) -> Mapped[datetime]:
        return mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    @declared_attr
    @classmethod
    def updated_at(cls) -> Mapped[datetime]:
        return mapped_column(
            DateTime(timezone=True),
            server_default=func.now(),
            onupdate=func.now(),
            nullable=False,
        )


class SoftDeleteMixin:
    """`deleted_at` for the 30-day restore window (FR-407).

    Every query on a soft-deletable table must filter `deleted_at IS NULL`, and
    every index on one is partial with the same predicate — otherwise deleted
    rows bloat the index and leak into results.
    """

    @declared_attr
    @classmethod
    def deleted_at(cls) -> Mapped[datetime | None]:
        return mapped_column(DateTime(timezone=True), nullable=True, index=False)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
